#!/usr/bin/python3
import struct
import sys

ops = ("halt", "nop", "loadi", "loadf", "mov", "cmp", 
       "shr", "shl", "xor", "add", "sub", 
       "mul", "div", "inc", "dec", "and", 
       "or", "call", "ret", "jump", "loop", 
       "jz", "jnz")

f_in = open(sys.argv[1],'r')
f_out =  open('bin.sbc', 'wb')

for line in f_in.readlines():
    inst = line.split()
    op = ops.index(inst[0])
    arg1 = int(inst[1])
    arg2 = int(inst[2])
    arg3 = int(inst[3])
    if op != 3:
        arg4 = int(inst[4])
        data = struct.pack('bbbbi', op, arg1, arg2, arg3, arg4)
    else:
        arg4 = float(inst[4])
        data = struct.pack('bbbbf', op, arg1, arg2, arg3, arg4)

    f_out.write(data)

f_in.close()
f_out.close()